language: ruby
bundler_args: --without benchmarks
script:
  - bundle exec rake spec
before_install:
  - gem --version
  - |
    bash -c " # Install MySQL 5.7 if DB=mysql57
    if [[ x$DB =~ mysql57 ]]; then
      sudo bash .travis_mysql57.sh
    fi
    "
  - |
    bash -c " # Install MariaDB if DB=mariadb
    if [[ x$DB =~ xmariadb ]]; then
      sudo bash .travis_mariadb.sh '$DB'
    fi
    "
  - |
    bash -c " # Install MySQL is OS=darwin
    if [[ x$OSTYPE =~ ^xdarwin ]]; then
      brew install mysql
      mysql.server start
    fi
    "
  - |
    bash -c " # Configure SSL support
    if [[ ! x$OSTYPE =~ ^xdarwin ]]; then
      sudo bash .travis_ssl.sh
      sudo service mysql restart
    fi
    "
  - mysqld --version
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS test"
  - mysql -u root -e "CREATE USER '$USER'@'localhost'" || true
os:
  - linux
rvm:
  - 2.4.1
matrix:
  allow_failures:
    - env: DB=mysql57
    - rvm: rbx-2
    - os: osx
